version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gofmt
    - misspell
    - unconvert
    - unparam

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - unparam
